version: '2'

services:
  postgres-agency-soap:
    container_name: victor-agency-soap-container
    image: victor/postgres-agency-soap
    build: ./agency-soap/postgres
    volumes:
      - ./agency-volume:/var/lib/postgresql
    ports:
      - 5433:5432

  agency-service-soap:
    container_name: victor-agency-soap-service-container
    image: victor/service-agency-soap
    build: ./agency-soap/
    ports:
      - 8081:8080
    depends_on:
      - postgres-agency-soap
