
package io.github.victorhsr.pos.soap.consumer;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ClientResources", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientResources {


    /**
     * 
     * @param clientId
     * @return
     *     returns io.github.victorhsr.pos.soap.consumer.Client
     */
    @WebMethod
    @WebResult(name = "client", targetNamespace = "")
    @RequestWrapper(localName = "getClient", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetClient")
    @ResponseWrapper(localName = "getClientResponse", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetClientResponse")
    public Client getClient(
        @WebParam(name = "clientId", targetNamespace = "")
        int clientId);

    /**
     * 
     * @param client
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "createClient", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.CreateClient")
    public void createClient(
        @WebParam(name = "client", targetNamespace = "")
        Client client);

    /**
     * 
     * @param client
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "updateClient", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.UpdateClient")
    public void updateClient(
        @WebParam(name = "client", targetNamespace = "")
        Client client);

    /**
     * 
     * @param client
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "excludeClient", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.ExcludeClient")
    public void excludeClient(
        @WebParam(name = "client", targetNamespace = "")
        Client client);

    /**
     * 
     * @return
     *     returns java.util.List<io.github.victorhsr.pos.soap.consumer.Client>
     */
    @WebMethod
    @WebResult(name = "clients", targetNamespace = "")
    @RequestWrapper(localName = "getClients", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetClients")
    @ResponseWrapper(localName = "getClientsResponse", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetClientsResponse")
    public List<Client> getClients();

}
