
package io.github.victorhsr.pos.soap.consumer;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PackageResources", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PackageResources {


    /**
     * 
     * @param _package
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "createPackage", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.CreatePackage")
    public void createPackage(
        @WebParam(name = "package", targetNamespace = "")
        Package _package);

    /**
     * 
     * @param _package
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "updatePackage", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.UpdatePackage")
    public void updatePackage(
        @WebParam(name = "package", targetNamespace = "")
        Package _package);

    /**
     * 
     * @param _package
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "excludePackage", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.ExcludePackage")
    public void excludePackage(
        @WebParam(name = "package", targetNamespace = "")
        Package _package);

    /**
     * 
     * @param packageId
     * @return
     *     returns io.github.victorhsr.pos.soap.consumer.Package
     */
    @WebMethod
    @WebResult(name = "package", targetNamespace = "")
    @RequestWrapper(localName = "getPackage", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetPackage")
    @ResponseWrapper(localName = "getPackageResponse", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetPackageResponse")
    public Package getPackage(
        @WebParam(name = "packageId", targetNamespace = "")
        int packageId);

    /**
     * 
     * @return
     *     returns java.util.List<io.github.victorhsr.pos.soap.consumer.Package>
     */
    @WebMethod
    @WebResult(name = "packages", targetNamespace = "")
    @RequestWrapper(localName = "getPackages", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetPackages")
    @ResponseWrapper(localName = "getPackagesResponse", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetPackagesResponse")
    public List<Package> getPackages();

}
