
package io.github.victorhsr.pos.soap.consumer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "passagem", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", wsdlLocation = "http://localhost:8080/passagem/TicketResource?WSDL")
public class Passagem
    extends Service
{

    private final static URL PASSAGEM_WSDL_LOCATION;
    private final static WebServiceException PASSAGEM_EXCEPTION;
    private final static QName PASSAGEM_QNAME = new QName("http://resources.agency.pos.victorhsr.github.io/", "passagem");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/passagem/TicketResource?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PASSAGEM_WSDL_LOCATION = url;
        PASSAGEM_EXCEPTION = e;
    }

    public Passagem() {
        super(__getWsdlLocation(), PASSAGEM_QNAME);
    }

    public Passagem(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns TicketResource
     */
    @WebEndpoint(name = "TicketResourcePort")
    public TicketResource getTicketResourcePort() {
        return super.getPort(new QName("http://resources.agency.pos.victorhsr.github.io/", "TicketResourcePort"), TicketResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketResource
     */
    @WebEndpoint(name = "TicketResourcePort")
    public TicketResource getTicketResourcePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resources.agency.pos.victorhsr.github.io/", "TicketResourcePort"), TicketResource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PASSAGEM_EXCEPTION!= null) {
            throw PASSAGEM_EXCEPTION;
        }
        return PASSAGEM_WSDL_LOCATION;
    }

}
