
package io.github.victorhsr.pos.soap.consumer;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TicketResource", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TicketResource {


    /**
     * 
     * @return
     *     returns java.util.List<io.github.victorhsr.pos.soap.consumer.Ticket>
     */
    @WebMethod
    @WebResult(name = "tickets", targetNamespace = "")
    @RequestWrapper(localName = "getTickets", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetTickets")
    @ResponseWrapper(localName = "getTicketsResponse", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetTicketsResponse")
    public List<Ticket> getTickets();

    /**
     * 
     * @param ticket
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "createTicket", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.CreateTicket")
    public void createTicket(
        @WebParam(name = "ticket", targetNamespace = "")
        Ticket ticket);

    /**
     * 
     * @param ticketId
     * @return
     *     returns io.github.victorhsr.pos.soap.consumer.Ticket
     */
    @WebMethod
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "getTicket", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetTicket")
    @ResponseWrapper(localName = "getTicketResponse", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.GetTicketResponse")
    public Ticket getTicket(
        @WebParam(name = "ticketId", targetNamespace = "")
        int ticketId);

    /**
     * 
     * @param ticket
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "updateTicket", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.UpdateTicket")
    public void updateTicket(
        @WebParam(name = "ticket", targetNamespace = "")
        Ticket ticket);

    /**
     * 
     * @param ticket
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "excludeTicket", targetNamespace = "http://resources.agency.pos.victorhsr.github.io/", className = "io.github.victorhsr.pos.soap.consumer.ExcludeTicket")
    public void excludeTicket(
        @WebParam(name = "ticket", targetNamespace = "")
        Ticket ticket);

}
